### ISSUE TITLE
有插件服务器启动失败

### ISSUE THREAD

**Issue by Jetkun** [FisherWY/Docker-CSGO#1]
在yaml配置路径无出错情况下，只要带有插件服务器就会启动失败

**Comment by FisherWY** [comment]
这种情况一般是使用了旧版的`metamod`和`sourcemod`插件引起的，可以通过更新插件的方法来解决

`metamod`官网：[https://www.sourcemm.net/](https://www.sourcemm.net/)

`sourcemod`官网：[https://www.sourcemod.net/](https://www.sourcemod.net/)

以更新`sourcemod`为例：
```bash
wget https://sm.alliedmods.net/smdrop/1.11/sourcemod-1.11.0-git6924-linux.tar.gz
# 解压到插件的存放目录中，覆盖掉旧版的sourcemod
tar zxvf sourcemod-1.11.0-git6924-linux.tar.gz -C /mod/retakes
```

重新启动Dockers容器，查看启动是否正常，一般情况下就恢复正常了

注意：覆盖更新插件时，会把管理员的配置文件也覆盖掉，注意备份
